name: Publish prereleases

on:
  push:
    branches: [experimental]
  # pull_request:

jobs:
  release:
    if: ${{ github.repository_owner == 'aziontech' }} # TODO: change to org opennextjs when ready
    name: Publish builder package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build
        run: pnpm -F azion run build
      # need install pkg-pr-new on organization aziontech
      # - name: Publish to NPM
      #   run: pnpm exec pkg-pr-new publish --pnpm --compact './packages/azion'
